[build]
  publish = "public"
  command = "npm install && npm run build"

[build.environment]
  HUGO_VERSION = "0.147.9"
  HUGO_BASEURL = "/"

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
